In [1]:
import numpy as np

In [2]:
A = np.array([[ 1, 2, 3],
              [ 4, 5, 6]])

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
B = np.array([[ 7, 8],
              [ 9, 10],
              [ 11, 12]])

In [5]:
B

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [6]:
C = np.dot(A, B)
C

array([[ 58,  64],
       [139, 154]])